# Generated by Django 3.2 on 2021-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='teg',
            field=models.CharField(choices=[('0', 'Завтрак'), ('1', 'Обед'), ('2', 'Ужин')], max_length=20, verbose_name='meal time'),
        ),
    ]
